### ISSUE TITLE
Listing existing images flags

### ISSUE THREAD

**Issue by CGandiaga** [giantswarm/retagger#263]
Hi! 
First of all, thank you very much for the retagger. It's useful and convenient in many ocassions. 

However, I find a little bit unconvenient the fact that, when trying to push to a private repository in Azure, if the image doesn't already exist the program crashes. Therefore I was wondering whether you could add a flag to decide if list-and-check the pre-existing images or not (so that it could work a little bit slower, but wouldn't find troubles when performing this operation mentioned above)

**Comment by calvix** [comment]
@CGandiaga Hello, I have introduced a new feature here: https://github.com/giantswarm/retagger/pull/287 which should create docker image repostiroy if it doesnt exists, this needs a support from docker registry and your user need to have permission to do so. That might help your issue.

**Comment by CGandiaga** [comment]
> @CGandiaga Hello, I have introduced a new feature here: #287 which should create docker image repostiroy if it doesnt exists, this needs a support from docker registry and your user need to have permission to do so. That might help your issue.

Hey! Thank you so much for developing it. It was a needed feature. Great job!!
