### ISSUE TITLE
Feature Request: Remote Docker Registry with Basic Auth

### ISSUE THREAD

**Issue by eyenx** [giantswarm/retagger#276]
Hi

Would be nice if not only public available Docker images could be retagged, but also private ones which need basic auth.

I would suggest passing the additional Remote Authentication via env variables or parameters:

```
REMOTE_REGISTRY_USERNAME
REMOTE_REGISTRY_PASSWORD
```

**Comment by MarcelMue** [comment]
Hey @eyenx - this should already be possible. See this example in our CI:

https://github.com/giantswarm/retagger/blob/1725bb28bc3d8ddb9e4fc4c066c06545fdfd3430/.circleci/config.yml#L82

Is this what you are looking for? I would expect this to be working just fine against private images.

Maybe I misunderstood and you want the source repository to be private as well?

**Comment by eyenx** [comment]
Yes sorry. I'm talking about the source repository.

**Comment by MarcelMue** [comment]
> Yes sorry. I'm talking about the source repository.

Little follow up question:
Would the registry be the same? E.g. would both of them be in `quay.io` with the same credentials?
If the credentials are different for pulling and pushing then this becomes a little more complex, as we would have to handle two different logins into repositories.
If it is the same set of credentials, then the change is pretty straight forward.

**Comment by eyenx** [comment]
Our use case is using a different source repo from the destination repo.

Wouldn't it be easier to just try and read already saved credentials in a.e. .docker/config.json ?

**Comment by mfriedenhagen** [comment]
* Now, that [hub.docker.com](https://www.docker.com/pricing/resource-consumption-updates) does limit the number of requests to 100 for anonymous and 200 for authenticated users this might get more urgent, especially for corporate users who all come from the same outgoing IP(s).
* I second @eyenx that just reusing the information from `.docker/config.json` seems like a good idea. 
* One caveat: What about people who use an [credentials-helper](https://github.com/docker/docker-credential-helpers)?
